/**
 * @file tbmodel.hpp
 * @brief Tight-binding model and operator builders.
 *
 * Reads the Wannier90 inputs (lattice vectors, orbital positions, Hamiltonian) and
 * builds derived real-space operators: velocity/current, density, spin density, and
 * spin current. Spin operators rely on orbital labels marking the spin channel
 * (`_s+_` / `_s-_`); spinless models produce zero for those operators.
 */
#ifndef TBMODELS
#define TBMODELS
#include <string>
#include <sstream>
#include <array>
#include <vector>
#include <tuple>
#include <complex>
#include <map>
#include <iostream>
#include <limits>
#include <cassert>
#include <stdexcept>
#include <functional>
#include <cmath>
#include<iostream>
#include<limits>
#include<algorithm>
#include "wannier_parser.hpp"
#include "hopping_list.hpp"

using namespace std;


/**
 * @brief Print and assert equality.
 * @tparam T comparable type
 * @param x first value
 * @param y second value
 */
template<typename T>
void assert_equal(const T x,const T y )
{
    if( x != y )
        std::cerr<<"ASSERT_EQUAL FAILED: "<<x<<" != "<<y<<std::endl;
    assert(x==y);
    return ;
}

/**
 * @brief Convert a cell vector to Cartesian coordinates.
 * @param tag integer cell index (Rx,Ry,Rz)
 * @param lat_vecs lattice vectors (rows)
 * @return Cartesian vector (Angstrom)
 */
array<double,3> tag2cartesian(const array<int,3>& tag,const array < array<double,3> , 3 >& lat_vecs  )
{
    array<double,3> cart_vect = {0,0,0};
    for(int i =0 ; i < cart_vect.size(); i++ )
    for(int j =0 ; j < tag.size(); j++ )
        cart_vect[i] += tag[j]*lat_vecs[j][i];
    return cart_vect;
};

/**
 * @brief Unit-cell volume.
 * @param uc 3x3 lattice vectors
 * @return volume in cubic Angstrom
 */
double volume( const array < array<double,3> , 3 >&  uc )
{
    return  std::fabs(
            ( uc[0][1]*uc[1][2]-uc[1][1]*uc[0][2])*uc[2][0]+
            ( uc[0][2]*uc[1][0]-uc[0][0]*uc[1][2])*uc[2][1]+
            ( uc[0][0]*uc[1][1]-uc[0][1]*uc[1][0])*uc[2][2]);
}

/**
 * @brief Tight-binding model built from Wannier90 output.
 *
 * Holds the unit cell, orbital positions, and the primitive-cell Hamiltonian as a
 * hopping_list. Provides builder methods for common operators used in KPM/Chebyshev
 * transport calculations.
 */
class tbmodel
{
    public:
    typedef tuple<string, array<double, 3> > orbPos_t;            ///< (label, Cartesian position)
    typedef array < array<double,3> , 3 > unitCell_t;             ///< 3x3 lattice vectors


    /**
     * @brief Read the unit-cell lattice vectors from `.uc`.
     * @param inputfile path to `.uc`
     */
    inline void readUnitCell(const string inputfile)
    {
        lat_vecs= read_unit_cell_file(inputfile);

    }

    /**
     * @brief Read orbital positions from `.xyz`.
     * @param inputfile path to `.xyz`
     */
    inline void readOrbitalPositions(const string inputfile)
    {
        orbPos_list= read_xyz_file(inputfile);
    };

    /**
     * @brief Read the Hamiltonian from `_hr.dat`.
     * @param inputfile path to `_hr.dat`
     */
    inline void readWannierModel(const string inputfile)
    {
        hl = create_hopping_list(read_wannier_file(inputfile));
    };

    /**
     * @brief Apply the Wigner-Seitz minimum-image correction from `_wsvec.dat`.
     * @param inputfile path to `_wsvec.dat`
     *
     * No-op if the file is absent.
     */
    inline void applyWsvec(const string inputfile)
    {
        hl = apply_wsvec(hl, read_wsvec(inputfile));
    };

    /**
     * @brief Load an arbitrary operator in `_hr.dat` format.
     * @param inputfile path to operator file
     * @return hopping_list representation
     *
     * Reuses the same parse + ndegen-normalize chain as the Hamiltonian. Enables
     * hand-built tight-binding models and externally generated operators.
     */
    inline hopping_list readOperatorModel(const string inputfile)
    {
        return create_hopping_list(read_wannier_file(inputfile));
    };

    /**
     * @brief Velocity (current) operator along a Cartesian axis.
     * @param dir direction index: 0=x, 1=y, 2=z
     * @return hopping_list representation of \f$J_{dir} = -i H \, dr_{dir}\f$
     *
     * Current operators are generated by multiplying each hopping by the Cartesian
     * displacement between its initial and final Wannier centers. Requires `.uc`
     * and `.xyz` to be loaded.
     */
    hopping_list createHoppingCurrents_list(const int dir)
    {
        std::cout<<"Creating the Current matrix J"<<dir<<std::endl;
        assert( dir <3 && dir >=0 );
        assert(volume(lat_vecs) > 0 );
        assert_equal( (int)orbPos_list.size(), hl.WannierBasisSize());

        hopping_list chl = this->hl ;
        for( auto& elem: chl.hoppings )
        {
            auto  tag   = get<0>(elem);
            auto  edge  = get<2>(elem);

            auto orb_diff = get<1>(orbPos_list[edge[1]]) ;//save final orbital position

            for( int i=0; i < orb_diff.size(); i++)
                orb_diff[i] +=-get<1>(orbPos_list[edge[0]])[i];//substract initial position

            auto displ_vec = tag2cartesian(tag, lat_vecs); //get the displacement vector in cartesian
            for( int i=0; i < orb_diff.size(); i++)
                orb_diff[i] += displ_vec[i];    //add it to the orbital_difference

            //Change the hopping element accordingly
            get<1>(elem) *=  hopping_list::value_t( 0.0, -orb_diff[dir] );
        }
        return chl;
    };


    /**
     * @brief Density operator: keep onsite terms, zero translations.
     * @return hopping_list representation of the density support
     */
    hopping_list createHoppingDensity_list()
    {
        assert(volume(lat_vecs) > 0 );
        assert(orbPos_list.size()==hl.WannierBasisSize());

        hopping_list chl = this->hl ;
        for( auto& elem: chl.hoppings )
        {
            auto  tag  = get<0>(elem);
            if( tag != hopping_list::cellID_t({0,0,0} ) )//Send to zero  non diagonal elements
                get<1>(elem) *=  0.0 ;
        }

        return chl;
    };

    /**
     * @brief Map orbital index to spin label.
     * @return map index -> +1 for `_s+_`, -1 for `_s-_`, 0 if unmarked
     */
    map<int,int>
    map_id2spin()
    {
        map<int,int> id2spin;
        int id = 0;
        for( auto orb_id : this->orbPos_list )
        {
            auto orb_label = get<0>(orb_id);
            int sz = 0 ;
            if( orb_label.find("_s+_")!=std::string::npos )
                sz= 1;
            if( orb_label.find("_s-_")!=std::string::npos )
                sz=-1;
            if( sz != 0)
                id2spin.insert( {id,sz} );
            id++;
        }
        return id2spin;
    }

    /**
     * @brief Orbital-base label = the orbital label with the sup/sdw spin tag removed.
     */
    static std::string orbital_base_label(std::string s)
    {
        for( const std::string tag : { std::string("_s+_"), std::string("_s-_") } )
        {
            auto p = s.find(tag);
            if( p != std::string::npos ) { s.erase(p, tag.size()); break; }
        }
        return s;
    }

    /**
     * @brief Pair each spinful orbital with its opposite-spin partner (sup/sdw).
     *
     * Spin-operator SUPPORT is built from the spin doubling, not from H's onsite graph.
     * Pairing convention: group by POSITION (primary); orbitals that share a site are
     * disambiguated by the orbital-base label (the label with the _s+_/_s-_ tag removed).
     * Each (position, base-label) group must hold exactly one up (_s+_) and one down
     * (_s-_); otherwise assert -- the model must label its spin channels unambiguously.
     * Spinless orbitals get no partner. The SOC `.spn` path (exact_spin_operator) is
     * untouched and unaffected.
     * @return map orbital index -> opposite-spin partner index (paired orbitals only)
     */
    map<int,int> map_id2partner()
    {
        auto id2spin = this->map_id2spin();
        auto q = [](double x){ return (long long) std::llround(x * 1e6); }; // quantize position
        map< tuple<long long,long long,long long,std::string>, pair<int,int> > grp; // key -> (up_id, down_id)
        int id = 0;
        for( auto& orb : orbPos_list )
        {
            int sz = id2spin.count(id) ? id2spin[id] : 0;
            if( sz != 0 )
            {
                auto& p = get<1>(orb);
                auto key = make_tuple( q(p[0]), q(p[1]), q(p[2]), orbital_base_label(get<0>(orb)) );
                if( grp.find(key) == grp.end() ) grp[key] = std::make_pair(-1,-1);
                int& slot = ( sz > 0 ) ? grp[key].first : grp[key].second;
                // Throw (not assert): assert is a no-op under NDEBUG -> silent-wrong spin
                // operators; a clear exception lets the caller fall back to the .spn route.
                if( slot != -1 )
                    throw std::runtime_error(
                        "map_id2partner: spin pairing ambiguous (>1 orbital with the same "
                        "position+base-label+spin). Use distinct orbital labels, or supply the "
                        "spin operators directly: --op-file SZ <seed>_Sz_hr.dat (from .spn / "
                        "export_operators.py), or --exact-spin.");
                slot = id;
            }
            id++;
        }
        map<int,int> partner;
        for( auto& kv : grp )
        {
            int up = kv.second.first, dn = kv.second.second;
            if( up == -1 || dn == -1 )
                throw std::runtime_error(
                    "map_id2partner: spin pairing incomplete (a position+base-label group lacks "
                    "an up or down partner) -- the label-based spin generator cannot pair this "
                    "model. Provide spin operators via --op-file S{X,Y,Z} <seed>_S{x,y,z}_hr.dat "
                    "(from .spn), or build exact spin with --exact-spin (.spn + _u.mat). A "
                    "tight-binding user can pass any precomputed *_hr.dat the same way.");
            partner[up] = dn;
            partner[dn] = up;
        }
        return partner;
    }

    /**
     * @brief Spin-density operator S_dir (dir = 'x','y','z'), Pauli convention (eig +/-1).
     * @return hopping_list representation
     *
     * The support is built from the SPIN DOUBLING (map_id2partner), NOT from the
     * Hamiltonian's onsite graph. This makes S_alpha a correct Pauli operator even when
     * the onsite block carries same-spin orbital bonds (e.g. graphene's intra-cell
     * sublattice bond, which the old density-support reuse turned into spurious S_z
     * off-diagonals with eigenvalues outside +/-1). Only onsite (R=0) 2x2 blocks per
     * spin pair are emitted:
     *     S_z = diag(+1,-1),  S_x: (up,down)=(down,up)=1,  S_y: (up,down)=-i,(down,up)=+i.
     * Spinless / unpaired orbitals contribute nothing (zero rows/cols).
     */
    hopping_list createHoppingSpinDensity_list(const char dir)
    {
        std::cout<<"Creating the spin Density matrix S"<<dir<<std::endl;
        auto id2spin = this->map_id2spin();
        auto partner = this->map_id2partner();

        hopping_list out = this->hl;   // inherit basis size + cell bounds
        out.hoppings.clear();          // support is rebuilt from the spin doubling
        const hopping_list::cellID_t R0 = {0,0,0};
        typedef hopping_list::value_t cplx;
        typedef hopping_list::edge_t  edge;

        for( auto& kv : partner )
        {
            const int i  = kv.first;       // this orbital
            const int j  = kv.second;      // its opposite-spin partner
            const int si = id2spin[i];     // +1 (up) or -1 (down)
            switch(dir)
            {
                case 'z':  // sigma_z : +/-1 on the diagonal
                    out.hoppings.push_back( make_tuple(R0, cplx((double)si, 0.0), edge({i,i})) );
                    break;
                case 'x':  // sigma_x : 1 on the up<->down off-diagonal (both directions)
                    out.hoppings.push_back( make_tuple(R0, cplx(1.0, 0.0), edge({i,j})) );
                    break;
                case 'y':  // sigma_y : (up,down)=-i, (down,up)=+i  -> value (0,-si)
                    out.hoppings.push_back( make_tuple(R0, cplx(0.0, (double)(-si)), edge({i,j})) );
                    break;
                default:
                    break;
            }
        }
        std::cout<<"Sucess."<<std::endl;
        return out;
    }


    /**
     * @brief Spin-current operator \f$J_{dir} S_{sdir}\f$.
     * @param dir velocity direction index (0=x, 1=y, 2=z)
     * @param sdir spin direction ('x', 'y', 'z')
     * @return hopping_list representation
     *
     * Spin currents are current operators projected through the selected spin Pauli
     * matrix in the same spin-resolved orbital ordering. Returns zero for a spinless
     * model.
     */
    /**
     * @brief Spin-current operator J^{sdir}_{dir} from the velocity and a Pauli spin factor.
     *
     * Multiplies each velocity element v_{ij}(R) by the per-element spin matrix factor.
     * This element-wise form equals the anticommutator J = 1/2{v, sigma} ONLY for the
     * DIAGONAL spin matrix sigma_z: (1/2{v,sigma_z})_{ij} = 1/2 v_{ij}(s_i+s_j), which is
     * v_{ij} s_i for same-spin (s_i=s_j) and ZERO for opposite-spin. The previous code
     * kept the opposite-spin block unchanged instead of zeroing it (a bug for SOC models
     * where v has spin-flip elements); fixed below.
     *
     * Warning: for the OFF-diagonal sigma_x/sigma_y the anticommutator mixes orbital
     * pairs and CANNOT be written as v_{ij} times a per-element factor. The element-wise
     * x/y values below are therefore NOT the true spin current; the authoritative route
     * for x/y is the supercell matrix anticommutator (CSR `--spin-current V S`, which
     * forms 1/2(V*S + S*V)). To-do: build the primitive J for all components as an
     * R-space anticommutator convolution of v(R) and S(R).
     */
    hopping_list createHoppingSpinCurrents_list(const int dir, const char sdir)
    {
        std::cout<<"Creating the spin Current matrix J"<<dir<<"S"<<sdir<<std::endl;
        auto id2spin = this->map_id2spin();
        auto curr = this->createHoppingCurrents_list(dir);
        for( auto& elem: curr.hoppings )
        {
            auto edge  = get<2>(elem);
            auto value =&get<1>(elem);
            auto s1=id2spin[edge[0]], s2= id2spin[edge[1]];
            if( s1!= 0 && s2!= 0 )
            switch(sdir)
            {
                case 'x':                                   // off-diagonal: see Warning above
                *value *= ( s1 + s2 == 0 ) ? hopping_list::value_t(1.0,0.0)
                                           : hopping_list::value_t(0.0,0.0);
                break;

                case 'y':                                   // off-diagonal: see Warning above
                *value *= ( s1 + s2 == 0 ) ? hopping_list::value_t(0.0,(double)s2)
                                           : hopping_list::value_t(0.0,0.0);
                break;

                case 'z':                                   // diagonal: exact anticommutator
                *value *= ( s1 == s2 ) ? hopping_list::value_t((double)s2,0.0)
                                       : hopping_list::value_t(0.0,0.0);  // zero opposite-spin (fix)
                break;

                default:
                    *value *= 0 ;
            }
        }
        std::cout<<"Sucess."<<std::endl;
        return curr;
    }


    int num_orbs;              ///< number of orbitals (redundant with orbPos_list.size())
    unitCell_t lat_vecs;       ///< unit-cell lattice vectors
    vector< orbPos_t > orbPos_list; ///< orbital positions
    hopping_list hl;           ///< primitive-cell Hamiltonian
};

#endif
