/**
 * @file tbmodel.hpp
 * @brief Tight-binding model and operator builders.
 *
 * Reads the Wannier90 inputs (lattice vectors, orbital positions, Hamiltonian) and
 * builds derived real-space operators: velocity/current, density, spin density, and
 * spin current. Spin operators rely on orbital labels marking the spin channel
 * (`_s+_` / `_s-_`); spinless models produce zero for those operators.
 */
#ifndef TBMODELS
#define TBMODELS
#include <string>
#include <sstream>
#include <array>
#include <vector>
#include <tuple>
#include <complex>
#include <map>
#include <iostream>
#include <limits>
#include <cassert>
#include <functional>
#include<iostream>
#include<limits>
#include<algorithm>
#include "wannier_parser.hpp"
#include "hopping_list.hpp"

using namespace std;


/**
 * @brief Print and assert equality.
 * @tparam T comparable type
 * @param x first value
 * @param y second value
 */
template<typename T>
void assert_equal(const T x,const T y )
{
    if( x != y )
        std::cerr<<"ASSERT_EQUAL FAILED: "<<x<<" != "<<y<<std::endl;
    assert(x==y);
    return ;
}

/**
 * @brief Convert a cell vector to Cartesian coordinates.
 * @param tag integer cell index (Rx,Ry,Rz)
 * @param lat_vecs lattice vectors (rows)
 * @return Cartesian vector (Angstrom)
 */
array<double,3> tag2cartesian(const array<int,3>& tag,const array < array<double,3> , 3 >& lat_vecs  )
{
    array<double,3> cart_vect = {0,0,0};
    for(int i =0 ; i < cart_vect.size(); i++ )
    for(int j =0 ; j < tag.size(); j++ )
        cart_vect[i] += tag[j]*lat_vecs[j][i];
    return cart_vect;
};

/**
 * @brief Unit-cell volume.
 * @param uc 3x3 lattice vectors
 * @return volume in cubic Angstrom
 */
double volume( const array < array<double,3> , 3 >&  uc )
{
    return  std::fabs(
            ( uc[0][1]*uc[1][2]-uc[1][1]*uc[0][2])*uc[2][0]+
            ( uc[0][2]*uc[1][0]-uc[0][0]*uc[1][2])*uc[2][1]+
            ( uc[0][0]*uc[1][1]-uc[0][1]*uc[1][0])*uc[2][2]);
}

/**
 * @brief Tight-binding model built from Wannier90 output.
 *
 * Holds the unit cell, orbital positions, and the primitive-cell Hamiltonian as a
 * hopping_list. Provides builder methods for common operators used in KPM/Chebyshev
 * transport calculations.
 */
class tbmodel
{
    public:
    typedef tuple<string, array<double, 3> > orbPos_t;            ///< (label, Cartesian position)
    typedef array < array<double,3> , 3 > unitCell_t;             ///< 3x3 lattice vectors


    /**
     * @brief Read the unit-cell lattice vectors from `.uc`.
     * @param inputfile path to `.uc`
     */
    inline void readUnitCell(const string inputfile)
    {
        lat_vecs= read_unit_cell_file(inputfile);

    }

    /**
     * @brief Read orbital positions from `.xyz`.
     * @param inputfile path to `.xyz`
     */
    inline void readOrbitalPositions(const string inputfile)
    {
        orbPos_list= read_xyz_file(inputfile);
    };

    /**
     * @brief Read the Hamiltonian from `_hr.dat`.
     * @param inputfile path to `_hr.dat`
     */
    inline void readWannierModel(const string inputfile)
    {
        hl = create_hopping_list(read_wannier_file(inputfile));
    };

    /**
     * @brief Apply the Wigner-Seitz minimum-image correction from `_wsvec.dat`.
     * @param inputfile path to `_wsvec.dat`
     *
     * No-op if the file is absent.
     */
    inline void applyWsvec(const string inputfile)
    {
        hl = apply_wsvec(hl, read_wsvec(inputfile));
    };

    /**
     * @brief Load an arbitrary operator in `_hr.dat` format.
     * @param inputfile path to operator file
     * @return hopping_list representation
     *
     * Reuses the same parse + ndegen-normalize chain as the Hamiltonian. Enables
     * hand-built tight-binding models and externally generated operators.
     */
    inline hopping_list readOperatorModel(const string inputfile)
    {
        return create_hopping_list(read_wannier_file(inputfile));
    };

    /**
     * @brief Velocity (current) operator along a Cartesian axis.
     * @param dir direction index: 0=x, 1=y, 2=z
     * @return hopping_list representation of \f$J_{dir} = -i H \, dr_{dir}\f$
     *
     * Current operators are generated by multiplying each hopping by the Cartesian
     * displacement between its initial and final Wannier centers. Requires `.uc`
     * and `.xyz` to be loaded.
     */
    hopping_list createHoppingCurrents_list(const int dir)
    {
        std::cout<<"Creating the Current matrix J"<<dir<<std::endl;
        assert( dir <3 && dir >=0 );
        assert(volume(lat_vecs) > 0 );
        assert_equal( (int)orbPos_list.size(), hl.WannierBasisSize());

        hopping_list chl = this->hl ;
        for( auto& elem: chl.hoppings )
        {
            auto  tag   = get<0>(elem);
            auto  edge  = get<2>(elem);

            auto orb_diff = get<1>(orbPos_list[edge[1]]) ;//save final orbital position

            for( int i=0; i < orb_diff.size(); i++)
                orb_diff[i] +=-get<1>(orbPos_list[edge[0]])[i];//substract initial position

            auto displ_vec = tag2cartesian(tag, lat_vecs); //get the displacement vector in cartesian
            for( int i=0; i < orb_diff.size(); i++)
                orb_diff[i] += displ_vec[i];    //add it to the orbital_difference

            //Change the hopping element accordingly
            get<1>(elem) *=  hopping_list::value_t( 0.0, -orb_diff[dir] );
        }
        return chl;
    };


    /**
     * @brief Density operator: keep onsite terms, zero translations.
     * @return hopping_list representation of the density support
     */
    hopping_list createHoppingDensity_list()
    {
        assert(volume(lat_vecs) > 0 );
        assert(orbPos_list.size()==hl.WannierBasisSize());

        hopping_list chl = this->hl ;
        for( auto& elem: chl.hoppings )
        {
            auto  tag  = get<0>(elem);
            if( tag != hopping_list::cellID_t({0,0,0} ) )//Send to zero  non diagonal elements
                get<1>(elem) *=  0.0 ;
        }

        return chl;
    };

    /**
     * @brief Map orbital index to spin label.
     * @return map index -> +1 for `_s+_`, -1 for `_s-_`, 0 if unmarked
     */
    map<int,int>
    map_id2spin()
    {
        map<int,int> id2spin;
        int id = 0;
        for( auto orb_id : this->orbPos_list )
        {
            auto orb_label = get<0>(orb_id);
            int sz = 0 ;
            if( orb_label.find("_s+_")!=std::string::npos )
                sz= 1;
            if( orb_label.find("_s-_")!=std::string::npos )
                sz=-1;
            if( sz != 0)
                id2spin.insert( {id,sz} );
            id++;
        }
        return id2spin;
    }

    /**
     * @brief Spin-density operator along a Cartesian axis.
     * @param dir spin direction: 'x', 'y', or 'z'
     * @return hopping_list representation
     *
     * Reuses the density support and replaces the values by the requested Pauli
     * matrix in the spin-resolved basis. Returns zero for a spinless model.
     */
    hopping_list createHoppingSpinDensity_list(const char dir)
    {
        std::cout<<"Creating the spin Density matrix S"<<dir<<std::endl;
        auto id2spin = this->map_id2spin();
        auto dens = this->createHoppingDensity_list();
        for( auto& elem: dens.hoppings )
        {
            auto cell  = get<0>(elem);
            auto edge  = get<2>(elem);
            auto value =&get<1>(elem);
            // Spin density is an ON-SITE operator: only the R=0 block carries it.
            // createHoppingDensity_list keeps the full Hamiltonian support with the
            // non-onsite VALUES merely zeroed; without this guard the s1==s2 branch
            // below would re-fill those zeroed same-spin bonds with +/-1, so e.g. a
            // collinear chain's S_z would inherit its +/-gamma hops and stop being
            // involutory (eigenvalues escape +/-1). Restrict the assignment to R=0.
            if( cell != hopping_list::cellID_t({0,0,0}) ) { *value = 0.0; continue; }
            auto s1=id2spin[edge[0]], s2= id2spin[edge[1]];
            // Pauli entry: assign the matching component, otherwise ZERO. (Previously
            // a non-matching entry kept its leftover density value -- e.g. S_x on a
            // collinear model retained the onsite +/-J_ex on the diagonal, which is
            // garbage, not sigma_x.) Spinless orbitals (s=0) contribute nothing.
            const bool spinful = ( s1 != 0 && s2 != 0 );
            switch(dir)
            {
                case 'x':   // sigma_x : 1 on up<->down off-diagonal
                    *value = ( spinful && s1 + s2 == 0 ) ? hopping_list::value_t(1.0, 0.0)
                                                         : hopping_list::value_t(0.0, 0.0);
                    break;
                case 'y':   // sigma_y : -i / +i on up<->down off-diagonal
                    *value = ( spinful && s1 + s2 == 0 ) ? hopping_list::value_t(0.0, (double)s2)
                                                         : hopping_list::value_t(0.0, 0.0);
                    break;
                case 'z':   // sigma_z : +/-1 on the spin-diagonal
                    *value = ( spinful && s1 == s2 ) ? hopping_list::value_t((double)s2, 0.0)
                                                     : hopping_list::value_t(0.0, 0.0);
                    break;
                default:
                    *value = 0 ;
            }
        }
        std::cout<<"Sucess."<<std::endl;
        return dens;
    }


    /**
     * @brief Spin-current operator \f$J_{dir} S_{sdir}\f$.
     * @param dir velocity direction index (0=x, 1=y, 2=z)
     * @param sdir spin direction ('x', 'y', 'z')
     * @return hopping_list representation
     *
     * Spin currents are current operators projected through the selected spin Pauli
     * matrix in the same spin-resolved orbital ordering. Returns zero for a spinless
     * model.
     */
    hopping_list createHoppingSpinCurrents_list(const int dir, const char sdir)
    {
        std::cout<<"Creating the spin Current matrix J"<<dir<<"S"<<sdir<<std::endl;
        auto id2spin = this->map_id2spin();
        auto curr = this->createHoppingCurrents_list(dir);
        for( auto& elem: curr.hoppings )
        {
            auto edge  = get<2>(elem);
            auto value =&get<1>(elem);
            auto s1=id2spin[edge[0]], s2= id2spin[edge[1]];
            if( s1!= 0 && s2!= 0 )
            switch(sdir)
            {
                case 'x':
                if( s1 + s2 == 0  )
                    *value *=1.0;
                break;

                case 'y':
                if( s1 + s2 == 0  )
                    *value *= hopping_list::value_t(0.0,s2);
                break;

                case 'z':
                if( s1 == s2 )
                    *value *= s2;
                    break;

                default:
                    *value *= 0 ;
            }
        }
        std::cout<<"Sucess."<<std::endl;
        return curr;
    }


    int num_orbs;              ///< number of orbitals (redundant with orbPos_list.size())
    unitCell_t lat_vecs;       ///< unit-cell lattice vectors
    vector< orbPos_t > orbPos_list; ///< orbital positions
    hopping_list hl;           ///< primitive-cell Hamiltonian
};

#endif
